<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm payment</name>
   <tag></tag>
   <elementGuidId>58da21e4-d747-4572-92bf-5eef47e369d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmPaymentBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='confirmPaymentBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ed9271c1-e96b-4805-9a69-ddf6d03d5b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa681f35-8f43-4022-a657-7103912fcd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmPaymentBtn</value>
      <webElementGuid>754e3a91-9949-4662-8c0f-ef567c5d9332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>confirmPayment('customer','1002', '1450.00' )</value>
      <webElementGuid>196c2fc4-8066-4d45-81b8-fda953f2f384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>min-w-[150px] px-6 py-3.5 text-sm bg-creamGold text-white rounded-md hover:bg-[#111]</value>
      <webElementGuid>687129af-a27a-46cd-ab49-1db65224b918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Confirm payment
                      </value>
      <webElementGuid>34d847d7-85f6-4968-9716-27eeea46b58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmPaymentBtn&quot;)</value>
      <webElementGuid>6630dec8-cb26-4e27-b611-f4518e1e25b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='confirmPaymentBtn']</value>
      <webElementGuid>bb6547c9-a06e-4f9d-a72d-4774c67fa460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='paymentForm']/div[2]/div[2]/button</value>
      <webElementGuid>cc8bbb9b-4a47-4a55-8ec2-5899a4a1c150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>6e50a44d-0525-4b2f-b53c-496dec5c3f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[1]/following::button[2]</value>
      <webElementGuid>c9e41fec-aebf-4343-be75-04b802be111f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm payment']/parent::*</value>
      <webElementGuid>7b013a81-66f4-4fe9-b08d-6e255575fdf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>c69c83bf-09f1-4a62-b59a-4598fdbdb4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'confirmPaymentBtn' and (text() = '
                        Confirm payment
                      ' or . = '
                        Confirm payment
                      ')]</value>
      <webElementGuid>c3e373e0-8823-411d-b650-b3fe20a9c48e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
