<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PROCEED TO CHECKOUT</name>
   <tag></tag>
   <elementGuidId>e0fc4df2-bf94-4f32-a9ca-3d6d8330744a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proceedToCheckoutBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='proceedToCheckoutBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8d32741-5f5e-4071-9274-76fd5ee8176a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proceedToCheckoutBtn</value>
      <webElementGuid>47cac0c4-27c9-4155-852e-b394912886f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-creamGold hover:bg-slate-500 text-white font-bold py-2 px-4 rounded</value>
      <webElementGuid>b8dca926-cb3d-4094-8fb0-b63a9d6e0175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROCEED TO CHECKOUT</value>
      <webElementGuid>d72d810a-efc0-4601-983b-d194c53f65d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proceedToCheckoutBtn&quot;)</value>
      <webElementGuid>fed17af9-1ee4-4fc5-b441-47b161aa0c4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='proceedToCheckoutBtn']</value>
      <webElementGuid>0b3734b8-78a9-40aa-bd08-4de42dbae204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THB 1450'])[1]/following::button[1]</value>
      <webElementGuid>08477a1b-5b8b-4253-93fc-9ab96012527c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grand Total:'])[1]/following::button[1]</value>
      <webElementGuid>e6ab8c00-8c12-4556-9f85-22dde40d62bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROCEED TO CHECKOUT']/parent::*</value>
      <webElementGuid>15c780bc-4166-4481-bb9b-1d88d09fb344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>bd0b0c4f-65d7-4294-84f6-52e7730f41de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'proceedToCheckoutBtn' and (text() = 'PROCEED TO CHECKOUT' or . = 'PROCEED TO CHECKOUT')]</value>
      <webElementGuid>0f990f75-fac4-40da-a297-a5948708afb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THB 1950'])[1]/following::button[1]</value>
      <webElementGuid>242b0dc1-7ae5-4bf0-ad7e-d7089f3f4054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
