<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery_orderCountry</name>
   <tag></tag>
   <elementGuidId>a5e8f9b2-6851-4ffd-94c7-f9b3d1e4bafd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#orderCountry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='orderCountry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e0586d3-fca9-4cbc-b064-bc7e42087663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17b37a97-0062-47b3-aa84-1acb54a82109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>orderCountry</value>
      <webElementGuid>fbbdf568-6bc6-4dc6-8234-a9dbe2e55a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Country</value>
      <webElementGuid>90f59ede-a01a-4d85-ab1a-9018f02c0106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-3.5 bg-gray-100 text-[#333] w-full text-sm border rounded-md focus:border-creamGold outline-none</value>
      <webElementGuid>93c5da3a-5d23-4ce8-9cea-8cfe1c0410c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderCountry&quot;)</value>
      <webElementGuid>24c342b2-0467-4d9a-9ac3-a8e7326925ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='orderCountry']</value>
      <webElementGuid>64aad76b-a00f-4aa2-b807-9d9e7cf338c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='paymentForm']/div/div/input[5]</value>
      <webElementGuid>9340fdba-414d-40d2-974a-069bc8bdad67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>4080736b-b191-4037-b106-5062ae362f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'orderCountry' and @placeholder = 'Country']</value>
      <webElementGuid>d37bcb22-5a20-468d-9719-33c82aeb40bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
