<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery_orderAddress</name>
   <tag></tag>
   <elementGuidId>ea1142d0-72d4-4376-8a67-67340acf1619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#orderAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='orderAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70bfe5ae-ec2d-4741-9cc4-b309ca140bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a63f43b-d59a-4981-8760-eaf8e0dd39d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>orderAddress</value>
      <webElementGuid>0ad700d6-d790-4675-9c31-4de48d7496c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>16906895-09f1-4609-aab1-5816f020a87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-3.5 bg-gray-100 text-[#333] w-full text-sm border rounded-md focus:border-creamGold outline-none</value>
      <webElementGuid>627c76cb-6177-41c3-8080-9cab4ef909e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderAddress&quot;)</value>
      <webElementGuid>dc189e48-1275-42ac-8215-bdc6d13ebffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='orderAddress']</value>
      <webElementGuid>88bd5ae1-c25c-4ebf-b6ef-a9ff0c119fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='paymentForm']/div/div/input[3]</value>
      <webElementGuid>ff76f5d9-9fba-41da-abd6-d467915bfa1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>84cd687c-7445-4ac8-a757-2d06d49bfc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'orderAddress' and @placeholder = 'Street address']</value>
      <webElementGuid>d3756ac7-3691-46c3-bd93-7d99e71af823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
