<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery_orderCity</name>
   <tag></tag>
   <elementGuidId>e9731a3c-a2e7-4898-a7df-f1ff4df2d10f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#orderCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='orderCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>046e6291-9603-44a4-93a6-aeb429123de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5d9ea89-f1b6-41d0-ac71-141a46772769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>orderCity</value>
      <webElementGuid>b6f9deeb-6f56-4030-8e86-0acf67b1e5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>e49d2023-ed08-43c4-83de-c675bf96713c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-3.5 bg-gray-100 text-[#333] w-full text-sm border rounded-md focus:border-creamGold outline-none</value>
      <webElementGuid>06de009a-c8e0-4ab4-9df4-2a2fa5ea904b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderCity&quot;)</value>
      <webElementGuid>ac79aebf-5cf0-426f-b371-05941030a34d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='orderCity']</value>
      <webElementGuid>42b93082-95f7-4719-b189-7cdd04b28a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='paymentForm']/div/div/input[4]</value>
      <webElementGuid>3f95793f-3f40-4fa4-a392-1d028b60b68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>5a7c5057-b019-4487-9a53-a4976bd830cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'orderCity' and @placeholder = 'City']</value>
      <webElementGuid>5a4a82a4-af6d-4b17-99ae-dcefcb8db694</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
