<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payment_payment_option</name>
   <tag></tag>
   <elementGuidId>235b48b0-4910-4a8e-8ec7-868a88a0c249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paypal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paypal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9b6eda9-7021-4f82-a309-7a625c783fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>22efb4de-11e8-4eb1-954b-27423453b28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_option</value>
      <webElementGuid>ba35a458-6b2c-4dad-bb6a-a9c060cf9864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-5 h-5 cursor-pointer</value>
      <webElementGuid>0c18a256-43ba-462d-83da-ea9122f385ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypal</value>
      <webElementGuid>20ac6eb6-4e94-4062-9c00-b782e81fd8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypal&quot;)</value>
      <webElementGuid>a69330df-e294-4cc0-bf10-83ca73caed56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paypal']</value>
      <webElementGuid>26b7ed06-5929-4d6c-ba05-c0de2475eae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payPaypal']/input</value>
      <webElementGuid>66efc945-ff56-4202-9bbb-7a6d0d644fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>afecfeb2-2189-4e6c-96e6-f3e26daa7370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'payment_option' and @id = 'paypal']</value>
      <webElementGuid>73a77a14-f38f-416d-8142-060640294993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
