<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery_orderEmail</name>
   <tag></tag>
   <elementGuidId>d95322ea-38ee-4f6b-986f-4728ab4f2a89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#orderEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='orderEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>970aa17d-bdaf-48b5-9984-5273b8cd193b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>589187d2-d1b6-473c-8d66-a1bf414eb807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>orderEmail</value>
      <webElementGuid>0b86b952-7b56-4bdc-8f4f-f80b9ca7e812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>a730855d-32b7-4464-ad55-e33750f16bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-3.5 bg-gray-100 text-[#333] w-full text-sm border rounded-md focus:border-creamGold outline-none</value>
      <webElementGuid>fa4154f0-f338-4c81-b191-5984d5764a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderEmail&quot;)</value>
      <webElementGuid>a9b128c9-bfa6-4c72-8459-d7ae32aeb45d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='orderEmail']</value>
      <webElementGuid>5f7ceedf-e428-40e1-884c-a99a1b47d0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='paymentForm']/div/div/input[2]</value>
      <webElementGuid>1c1a04c3-65c1-45ae-aa2e-4445e23a1ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>a5820f9a-72c0-4574-a7ae-e9ea70e689a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'orderEmail' and @placeholder = 'Email address']</value>
      <webElementGuid>2fdc161a-4034-4994-9b65-d84221ff24b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
