<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery_orderPostal</name>
   <tag></tag>
   <elementGuidId>ed272c0b-0c7e-4294-acbc-55563579f448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#orderPostal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='orderPostal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>209496fa-67ca-4f1b-b4f5-7a77bd2cba78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>33ddad13-73ba-4c77-b749-87d36ce2f38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>orderPostal</value>
      <webElementGuid>c4945304-7740-4992-a574-c9cabc14efb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Postal code</value>
      <webElementGuid>05164f7a-fce6-4823-83a4-561e315a1ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-3.5 bg-gray-100 text-[#333] w-full text-sm border rounded-md focus:border-creamGold outline-none</value>
      <webElementGuid>b2b3ad6d-ae28-4791-89d5-2a714c7c57af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderPostal&quot;)</value>
      <webElementGuid>7cd491fc-93ff-4eaa-89df-219cb02d4bcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='orderPostal']</value>
      <webElementGuid>6bc2e91f-7189-4adc-b8ee-ef406033118c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='paymentForm']/div/div/input[6]</value>
      <webElementGuid>b23deaf4-4f70-4167-9d95-32bf9fcf9865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>d8416e62-88c3-4b12-88e1-e3219a2bcffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'orderPostal' and @placeholder = 'Postal code']</value>
      <webElementGuid>7984438d-de2c-4b8b-9fcb-453a6520a9ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
