<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery_orderName</name>
   <tag></tag>
   <elementGuidId>04f2c8f5-2208-495c-a620-e5c7a420e90a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#orderName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='orderName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b92414c9-230a-4f4a-a212-32eb18b80fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11786425-0a58-4417-8f85-cc8a372aad46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>orderName</value>
      <webElementGuid>752e04f8-fd84-40ce-9a09-86d46bb99e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>06774125-e8f2-489d-8e6d-1a7345cd675c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-3.5 bg-gray-100 text-[#333] w-full text-sm border rounded-md focus:border-creamGold outline-none</value>
      <webElementGuid>03893f67-a02a-4855-a6a2-ed1e3fd48517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderName&quot;)</value>
      <webElementGuid>48bf3d27-2863-4faa-b74a-64d6287c2455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='orderName']</value>
      <webElementGuid>4a9b7955-a505-463c-aaac-43100abfbc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='paymentForm']/div/div/input</value>
      <webElementGuid>f78f9516-44e0-4e86-a10f-4d8948f8ff6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cf4f6086-e425-45f0-8eb1-7a3047d53b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'orderName' and @placeholder = 'Name']</value>
      <webElementGuid>7a3224c9-b132-4f66-ad5e-1a4f207b6e90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
