<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WOMEN</name>
   <tag></tag>
   <elementGuidId>247690aa-6b60-4b3c-a6d5-b7c3c2822b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'WOMEN')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d551e18-0a3d-4f24-9e4a-853925b028c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/product/women</value>
      <webElementGuid>a3b9b1cc-de45-4ccd-b166-bdd4b6d0e73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 transition-colors duration-300 transform lg:mt-0 lg:mx-4 hover:text-creamGold text-xl</value>
      <webElementGuid>08d7be78-4cdf-448f-b8d0-5fa71356105a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WOMEN</value>
      <webElementGuid>ed822647-6515-4952-9855-2f4fc4dee309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-smokeWhite font-inria&quot;]/nav[@class=&quot;bg-white shadow&quot;]/div[@class=&quot;px-2 py-4 mx-5 max-sm:mx-0 lg:w-4/5 lg:mx-auto&quot;]/div[@class=&quot;lg:flex lg:items-center&quot;]/div[@class=&quot;absolute inset-x-0 z-20 flex-1 w-full px-6 py-4 transition-all duration-300 ease-in-out bg-creamGold lg:mt-0 lg:p-0 lg:top-0 lg:relative lg:bg-transparent lg:w-auto lg:opacity-100 lg:translate-x-0 lg:flex lg:items-center lg:justify-between opacity-0 -translate-x-full&quot;]/div[@class=&quot;flex flex-col font-inria dark:text-black lg:flex lg:px-16 lg:-mx-4 lg:flex-row lg:items-center lg:justify-center w-full&quot;]/a[@class=&quot;mt-2 transition-colors duration-300 transform lg:mt-0 lg:mx-4 hover:text-creamGold text-xl&quot;]</value>
      <webElementGuid>83e7e38b-761f-4313-a6ba-6d544ba98b5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WOMEN')]</value>
      <webElementGuid>5c0bf45e-0e70-402e-a48e-f3a3697c0dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::a[1]</value>
      <webElementGuid>a4a249d5-8137-411d-9632-2229f07c5724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEN'])[1]/preceding::a[1]</value>
      <webElementGuid>4d484fbe-a737-4955-b558-ade256acb8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNISEX'])[1]/preceding::a[2]</value>
      <webElementGuid>f76864ea-ac90-4930-af8a-aca61b9130ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WOMEN']/parent::*</value>
      <webElementGuid>fd02c79a-c507-46b3-a1d3-57f056ec1db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/product/women')]</value>
      <webElementGuid>c218dc64-fe2a-4039-a687-305bd42cbc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>5347a998-670b-4a86-bf79-db9221a3fe84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/product/women' and (text() = 'WOMEN' or . = 'WOMEN')]</value>
      <webElementGuid>eb8a9e1c-ac46-4f4f-a535-a6f9403b5f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
