<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_search_rounded-lg</name>
   <tag></tag>
   <elementGuidId>5769dd09-abce-4d4c-944f-3a5c10a95db9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@name=''])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8ae6aacc-d7d1-4413-9efe-8856cab87a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://myserenebucket.s3.amazonaws.com/asset-20240309T155047Z-001/asset/Women/greenriverdess.png</value>
      <webElementGuid>71b5bbf0-c478-41fe-9b64-38ca524752a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Greem River Dress</value>
      <webElementGuid>9e7b901e-3261-42c7-a843-48f5a78ba690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-lg</value>
      <webElementGuid>ea6858d4-c625-4d4b-b377-b2dea1993ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products&quot;)/div[@class=&quot;mx-auto flex flex-wrap items-center w-full mt-5&quot;]/div[@class=&quot;grid grid-cols-2 lg:grid-cols-4 gap-5 mx-auto px-5 w-full&quot;]/div[@class=&quot;overflow-hidden flex justify-center items-center flex-col w-1/2 mx-auto m-3&quot;]/div[@class=&quot;product&quot;]/a[1]/img[@class=&quot;rounded-lg&quot;]</value>
      <webElementGuid>0cf6d52f-71c4-4c11-8770-2b4aeb2a4abb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@name=''])[6]</value>
      <webElementGuid>ee49677b-e41e-4f0e-9e30-2ec45b403e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='products']/div[2]/div/div[6]/div/a/img</value>
      <webElementGuid>b3c8b321-d20a-4af8-a55c-66c82c8e03d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Greem River Dress']</value>
      <webElementGuid>052073f2-5626-4a05-9e89-dd27318c0784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a/img</value>
      <webElementGuid>dffcbc53-8d32-4353-91fd-730477f17085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://myserenebucket.s3.amazonaws.com/asset-20240309T155047Z-001/asset/Women/greenriverdess.png' and @alt = 'Greem River Dress']</value>
      <webElementGuid>11b977f3-3963-4d3e-956f-c8b7c1780776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
