<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Your Cart</name>
   <tag></tag>
   <elementGuidId>bf120d77-613f-4b96-b5fa-5957d8dec9ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cartCount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='cartCount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>934b0eca-573a-4025-ab0c-a640ad1a5685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cartCount</value>
      <webElementGuid>cccc6716-433b-4452-9e62-f3c6ed10df49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-10 mb-20 text-3xl sm:w-1/3 text-center</value>
      <webElementGuid>2506e93a-abd2-470f-8bd1-a7ac15a472cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your Cart</value>
      <webElementGuid>c758eff5-2ffe-4443-9b2e-2c7010b226c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartCount&quot;)</value>
      <webElementGuid>2fe66d1c-e277-4410-ab16-97c1ee920081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='cartCount']</value>
      <webElementGuid>c9482e1e-8473-4b28-a169-34eb9b3d3050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[2]/following::p[1]</value>
      <webElementGuid>7444ac11-0772-4a90-a3e9-ec2e466c4704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT'])[1]/following::p[2]</value>
      <webElementGuid>d4dd93a1-9deb-4a17-9c95-000e63c1e06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items'])[1]/preceding::p[1]</value>
      <webElementGuid>b1f06a5e-0887-4f19-9748-9c8290a86f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[1]/preceding::p[1]</value>
      <webElementGuid>43240447-5ffe-4a76-9bf6-ce0babe4e381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your Cart']/parent::*</value>
      <webElementGuid>49e1b08c-3cba-47d6-a170-1be1bfff52a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/p</value>
      <webElementGuid>be59803f-7a05-4c89-a289-0994d2267c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'cartCount' and (text() = 'Your Cart' or . = 'Your Cart')]</value>
      <webElementGuid>502a7f7b-c56a-4be3-9bda-801c35e5c4fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
